# Generated by Django 4.2.13 on 2026-02-06 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="category",
            field=models.CharField(
                choices=[
                    ("ELECTRONICS", "Electronics"),
                    ("BAGS_AND_CARRY", "Bags and Carry"),
                    ("CLOTHING_AND_WEARABLES", "Clothing and wearables"),
                    ("BOTTLES_AND_CONTAINERS", "Bottles and containers"),
                    ("DOCUMENTS_AND_IDS", "Documents and Id's"),
                    ("NOTEBOOKS_AND_BOOKS", "Notebooks/books"),
                    ("OTHER_MISC", "Other/Misc"),
                ],
                db_index=True,
                default="OTHER_MISC",
                max_length=40,
            ),
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(
                fields=["category"], name="inventory_i_categor_bf879d_idx"
            ),
        ),
    ]
