# Generated by Django 4.2.13 on 2026-02-06 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_item_category_item_inventory_i_categor_bf879d_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="claimed_at",
            field=models.DateTimeField(
                blank=True, help_text="When this item was claimed", null=True
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="claimed_by_name",
            field=models.CharField(
                blank=True,
                help_text="Name of person who claimed this item",
                max_length=255,
            ),
        ),
    ]
