# Generated by Django 4.2.13 on 2026-02-18 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("inventory", "0005_claim"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentLostItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "email_subject",
                    models.CharField(
                        help_text="Original email subject", max_length=500
                    ),
                ),
                (
                    "email_from",
                    models.EmailField(
                        help_text="Email address of the student who submitted",
                        max_length=254,
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "approval_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={"ordering": ["-submitted_at"],},
        ),
        migrations.CreateModel(
            name="StudentLostItemImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="student_item_images/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_super_user",
                    models.BooleanField(
                        default=False,
                        help_text="Super Users can approve items and upload without approval",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="item",
            name="approval_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                ],
                db_index=True,
                default="APPROVED",
                help_text="Approval status for admin-uploaded items",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="item_type",
            field=models.CharField(
                choices=[("SENIOR", "Senior Years"), ("PY", "Primary Years")],
                db_index=True,
                default="SENIOR",
                help_text="Whether this item is for Senior Years or Primary Years",
                max_length=10,
            ),
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(
                fields=["approval_status"], name="inventory_i_approva_420c30_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(
                fields=["item_type"], name="inventory_i_item_ty_3448a3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(
                fields=["approval_status", "item_type"],
                name="inventory_i_approva_b0d203_idx",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lost_found_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="studentlostitemimage",
            name="student_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="inventory.studentlostitem",
            ),
        ),
        migrations.AddField(
            model_name="studentlostitem",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="student_items_approved",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="studentlostitem",
            index=models.Index(
                fields=["approval_status"], name="inventory_s_approva_be34d4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentlostitem",
            index=models.Index(
                fields=["submitted_at"], name="inventory_s_submitt_1b0bda_idx"
            ),
        ),
    ]
