# Generated by Django 4.2.13 on 2026-02-18 18:57

from django.db import migrations


def set_existing_items_approved(apps, schema_editor):
    """Set all existing items to APPROVED status and SENIOR item_type."""
    Item = apps.get_model('inventory', 'Item')
    Item.objects.all().update(
        approval_status='APPROVED',
        item_type='SENIOR',
    )


def reverse_set_existing_items_approved(apps, schema_editor):
    """Reverse migration - set items back to PENDING (not really needed but for completeness)."""
    Item = apps.get_model('inventory', 'Item')
    # We don't really want to reverse this, but if needed:
    Item.objects.filter(approval_status='APPROVED').update(approval_status='PENDING')


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0006_studentlostitem_studentlostitemimage_userprofile_and_more"),
    ]

    operations = [
        migrations.RunPython(set_existing_items_approved, reverse_set_existing_items_approved),
    ]
