# Generated by Django 4.2.13 on 2026-02-22 10:20

from django.db import migrations
from django.contrib.auth import get_user_model


def promote_existing_superusers(apps, schema_editor):
    """Promote all users with is_super_user=True to Django superusers."""
    User = get_user_model()
    UserProfile = apps.get_model('inventory', 'UserProfile')
    
    # Find all users with is_super_user=True
    super_user_profiles = UserProfile.objects.filter(is_super_user=True)
    
    promoted_count = 0
    for profile in super_user_profiles:
        user = profile.user
        if not user.is_superuser:
            user.is_superuser = True
            if not user.is_staff:
                user.is_staff = True
            user.save()
            promoted_count += 1


def reverse_promote_existing_superusers(apps, schema_editor):
    """Reverse migration - this is a one-way migration, no reverse needed."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0007_set_existing_items_approved"),
    ]

    operations = [
        migrations.RunPython(promote_existing_superusers, reverse_promote_existing_superusers),
    ]
