# Generated by Django 4.2.13 on 2026-02-22 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0008_promote_existing_superusers"),
    ]

    operations = [
        migrations.RemoveField(model_name="userprofile", name="is_super_user",),
    ]
