# Generated by Django 4.2.13 on 2026-02-26 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0009_remove_is_super_user_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="claim",
            name="claimant_email",
            field=models.EmailField(
                blank=True,
                default="",
                help_text="Email of the person claiming this item",
                max_length=254,
            ),
        ),
    ]
