# Generated by Django 4.2.13 on 2026-06-24 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("inventory", "0010_claim_claimant_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="MicrosoftOAuthToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "account_email",
                    models.EmailField(
                        help_text="The mailbox the token authorizes access to.",
                        max_length=254,
                    ),
                ),
                (
                    "encrypted_refresh_token",
                    models.BinaryField(help_text="Fernet-encrypted refresh token."),
                ),
                (
                    "cached_access_token",
                    models.TextField(
                        blank=True,
                        help_text="Last access token in cleartext, valid until cached_access_token_expires_at.",
                    ),
                ),
                (
                    "cached_access_token_expires_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "scopes",
                    models.TextField(
                        help_text="Space-separated scopes the token grants."
                    ),
                ),
                ("last_refreshed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Microsoft OAuth Token",
                "verbose_name_plural": "Microsoft OAuth Tokens",
            },
        ),
        migrations.AddField(
            model_name="item",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="items_approved",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="rejection_reason",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="studentlostitem",
            name="needs_review_reason",
            field=models.CharField(
                blank=True,
                help_text="Semicolon-separated canonical review reasons",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="studentlostitem",
            name="rejection_reason",
            field=models.CharField(
                blank=True,
                help_text="Reason for rejection provided by staff",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="studentlostitem",
            name="source_message_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Email Message-ID for deduplication",
                max_length=998,
            ),
        ),
        migrations.AddField(
            model_name="studentlostitem",
            name="submitter_display_name",
            field=models.CharField(
                blank=True,
                help_text="Display name parsed from the email From header",
                max_length=200,
            ),
        ),
        migrations.CreateModel(
            name="MagicLinkRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(db_index=True, max_length=254)),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=500)),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-requested_at"],
                "indexes": [
                    models.Index(
                        fields=["email", "-requested_at"],
                        name="inventory_m_email_c15ef6_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="UserRoleChangeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_username_snapshot",
                    models.CharField(
                        help_text="Username at time of change (in case the user is later deleted).",
                        max_length=150,
                    ),
                ),
                (
                    "performed_by_username_snapshot",
                    models.CharField(blank=True, max_length=150),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "User created"),
                            ("PROMOTE_ADMIN", "Granted Admin access"),
                            ("PROMOTE_SUPERUSER", "Granted Super User access"),
                            ("DEMOTE_TO_ADMIN", "Demoted from Super User to Admin"),
                            ("REVOKE_STAFF", "Revoked staff access"),
                            ("DEACTIVATE", "Deactivated"),
                            ("REACTIVATE", "Reactivated"),
                            ("DELETE", "Deleted"),
                            ("EDIT_PROFILE", "Profile edited (name/email)"),
                            ("PASSWORD_RESET", "Password reset by Super User"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "details",
                    models.TextField(
                        blank=True,
                        help_text="Free-text details, e.g. 'is_staff: False → True; is_superuser: False → True'.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="role_changes_performed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_user",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user whose role was changed. SET_NULL so the log survives user deletion.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="role_changes_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["target_user", "-created_at"],
                        name="inventory_u_target__7ed4cd_idx",
                    ),
                    models.Index(
                        fields=["-created_at"], name="inventory_u_created_154a44_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="BroadcastLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("STUDENT_LOST", "Student lost item"),
                            ("FOUND_ITEM", "Found item"),
                        ],
                        max_length=20,
                    ),
                ),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recipients",
                    models.TextField(
                        help_text="Comma-separated recipient addresses at time of send."
                    ),
                ),
                ("subject", models.CharField(max_length=255)),
                (
                    "body_preview",
                    models.TextField(
                        help_text="First 1000 chars of the body sent, for audit."
                    ),
                ),
                ("succeeded", models.BooleanField(default=False)),
                ("error_message", models.TextField(blank=True)),
                (
                    "found_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="broadcasts",
                        to="inventory.item",
                    ),
                ),
                (
                    "sent_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="broadcasts_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student_lost_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="broadcasts",
                        to="inventory.studentlostitem",
                    ),
                ),
            ],
            options={
                "ordering": ["-sent_at"],
                "indexes": [
                    models.Index(
                        fields=["kind", "-sent_at"], name="inventory_b_kind_c2fe43_idx"
                    )
                ],
            },
        ),
    ]
