# Generated by Django 4.2.13 on 2026-06-24 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0012_backfill_item_approval_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="status",
            field=models.CharField(
                choices=[
                    ("FOUND", "Found"),
                    ("CLAIMED", "Claimed"),
                    ("COLLECTED", "Collected by Student"),
                ],
                db_index=True,
                default="FOUND",
                max_length=20,
            ),
        ),
    ]
